/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import java.awt.Color;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class InsertFactura extends javax.swing.JFrame {

    /**
     * Creates new form InsertClient
     */
    public Statement sql;
    int xMouse, yMouse;
    
    int Itemnumdisp; 
    int ItemnumAcc;
    int[] DispoComp;
    int[] AccComp;
    
    
    
    public InsertFactura() {
        initComponents();
        setLocationRelativeTo(null);
        
        Itemnumdisp = 0;
        ItemnumAcc = 0;
        DispoComp = new int[60];
        AccComp = new int[60];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facturaFormBG = new javax.swing.JPanel();
        tipoProdSelect = new javax.swing.JComboBox<>();
        itemIdTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsToPurchaseTextArea = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        facturaLabel = new javax.swing.JLabel();
        purchaseLabel = new javax.swing.JLabel();
        cliIdTextField = new javax.swing.JTextField();
        cliIDLabel = new javax.swing.JLabel();
        itemIdLabel = new javax.swing.JLabel();
        modIDLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        windowActions = new javax.swing.JPanel();
        minimizeButton = new javax.swing.JPanel();
        minimizeLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        blueStripe = new javax.swing.JPanel();
        redStripe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        catalog = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        insert = new javax.swing.JButton();
        edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        facturaFormBG.setBackground(new java.awt.Color(247, 247, 247));
        facturaFormBG.setPreferredSize(new java.awt.Dimension(740, 500));
        facturaFormBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipoProdSelect.setBackground(new java.awt.Color(194, 200, 203));
        tipoProdSelect.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tipoProdSelect.setForeground(new java.awt.Color(27, 47, 59));
        tipoProdSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dispo", "Acc" }));
        tipoProdSelect.setSelectedIndex(-1);
        tipoProdSelect.setBorder(null);
        facturaFormBG.add(tipoProdSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 130, 25));

        itemIdTextField.setBackground(new java.awt.Color(194, 200, 203));
        itemIdTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        itemIdTextField.setForeground(new java.awt.Color(27, 47, 59));
        itemIdTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        facturaFormBG.add(itemIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 130, 25));

        itemsToPurchaseTextArea.setBackground(new java.awt.Color(194, 200, 203));
        itemsToPurchaseTextArea.setColumns(20);
        itemsToPurchaseTextArea.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        itemsToPurchaseTextArea.setForeground(new java.awt.Color(27, 47, 59));
        itemsToPurchaseTextArea.setRows(5);
        itemsToPurchaseTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jScrollPane1.setViewportView(itemsToPurchaseTextArea);

        facturaFormBG.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 230, 160));

        addButton.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        addButton.setForeground(new java.awt.Color(27, 47, 59));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacion/Imagenes/buttonColor1.png"))); // NOI18N
        addButton.setText("Add");
        addButton.setBorder(null);
        addButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addButtonMouseExited(evt);
            }
        });
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        facturaFormBG.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 255, 80, 30));

        confirmButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(27, 47, 59));
        confirmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacion/Imagenes/buttonColor1.png"))); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.setBorder(null);
        confirmButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmButtonMousePressed(evt);
            }
        });
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        facturaFormBG.add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 110, 40));

        facturaLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        facturaLabel.setForeground(new java.awt.Color(27, 47, 59));
        facturaLabel.setText("Receipt");
        facturaFormBG.add(facturaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        purchaseLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        purchaseLabel.setForeground(new java.awt.Color(27, 47, 59));
        purchaseLabel.setText("Purchase");
        facturaFormBG.add(purchaseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 60, -1));

        cliIdTextField.setBackground(new java.awt.Color(194, 200, 203));
        cliIdTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cliIdTextField.setForeground(new java.awt.Color(27, 47, 59));
        cliIdTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        facturaFormBG.add(cliIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 130, 25));

        cliIDLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cliIDLabel.setForeground(new java.awt.Color(27, 47, 59));
        cliIDLabel.setText("Client ID");
        facturaFormBG.add(cliIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        itemIdLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        itemIdLabel.setForeground(new java.awt.Color(27, 47, 59));
        itemIdLabel.setText("Item ID");
        facturaFormBG.add(itemIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        modIDLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        modIDLabel2.setForeground(new java.awt.Color(27, 47, 59));
        modIDLabel2.setText("Type");
        facturaFormBG.add(modIDLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 80, -1));

        backButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(27, 47, 59));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacion/Imagenes/buttonColor1.png"))); // NOI18N
        backButton.setText("Back");
        backButton.setBorder(null);
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backButtonMousePressed(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        facturaFormBG.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 110, 40));

        headerPanel.setBackground(new java.awt.Color(194, 200, 203));
        headerPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerPanelMouseDragged(evt);
            }
        });
        headerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerPanelMousePressed(evt);
            }
        });

        windowActions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizeButton.setBackground(new java.awt.Color(194, 200, 203));

        minimizeLabel.setBackground(new java.awt.Color(247, 247, 247));
        minimizeLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        minimizeLabel.setForeground(new java.awt.Color(27, 47, 59));
        minimizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLabel.setText("—");
        minimizeLabel.setToolTipText("");
        minimizeLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        minimizeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout minimizeButtonLayout = new javax.swing.GroupLayout(minimizeButton);
        minimizeButton.setLayout(minimizeButtonLayout);
        minimizeButtonLayout.setHorizontalGroup(
            minimizeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        minimizeButtonLayout.setVerticalGroup(
            minimizeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimizeButtonLayout.createSequentialGroup()
                .addComponent(minimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        windowActions.add(minimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        exitButton.setBackground(new java.awt.Color(194, 200, 203));

        exitLabel.setBackground(new java.awt.Color(247, 247, 247));
        exitLabel.setFont(new java.awt.Font("Roboto", 1, 19)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(27, 47, 59));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitButtonLayout = new javax.swing.GroupLayout(exitButton);
        exitButton.setLayout(exitButtonLayout);
        exitButtonLayout.setHorizontalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );
        exitButtonLayout.setVerticalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        windowActions.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, -1));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(0, 660, Short.MAX_VALUE)
                .addComponent(windowActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(windowActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        facturaFormBG.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        blueStripe.setBackground(new java.awt.Color(27, 47, 59));

        redStripe.setBackground(new java.awt.Color(211, 22, 34));

        javax.swing.GroupLayout redStripeLayout = new javax.swing.GroupLayout(redStripe);
        redStripe.setLayout(redStripeLayout);
        redStripeLayout.setHorizontalGroup(
            redStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
        redStripeLayout.setVerticalGroup(
            redStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 247, 247));
        jLabel1.setText("Insert");

        catalog.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        catalog.setForeground(new java.awt.Color(247, 247, 247));
        catalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacion/Imagenes/buttonColor7.png"))); // NOI18N
        catalog.setText("Catalog");
        catalog.setBorder(null);
        catalog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        catalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                catalogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                catalogMouseExited(evt);
            }
        });
        catalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogActionPerformed(evt);
            }
        });

        menu.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        menu.setForeground(new java.awt.Color(247, 247, 247));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacion/Imagenes/buttonColor7.png"))); // NOI18N
        menu.setText("Menu");
        menu.setBorder(null);
        menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
        });
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        insert.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        insert.setForeground(new java.awt.Color(247, 247, 247));
        insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacion/Imagenes/buttonColor6.png"))); // NOI18N
        insert.setText("Insert");
        insert.setBorder(null);
        insert.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        edit.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        edit.setForeground(new java.awt.Color(247, 247, 247));
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacion/Imagenes/buttonColor7.png"))); // NOI18N
        edit.setText("Database");
        edit.setBorder(null);
        edit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMouseExited(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout blueStripeLayout = new javax.swing.GroupLayout(blueStripe);
        blueStripe.setLayout(blueStripeLayout);
        blueStripeLayout.setHorizontalGroup(
            blueStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blueStripeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(blueStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catalog, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(blueStripeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(redStripe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blueStripeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(52, 52, 52))
        );
        blueStripeLayout.setVerticalGroup(
            blueStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blueStripeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redStripe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catalog, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        facturaFormBG.add(blueStripe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facturaFormBG, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facturaFormBG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        TableSelect selectTable = new TableSelect();
        selectTable.sql = this.sql;
        selectTable.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        ImageIcon image = new ImageIcon("src/aplicacion/Imagenes/buttonColor2.png");
        backButton.setIcon(image);
    }//GEN-LAST:event_backButtonMouseEntered

    private void backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseExited
        ImageIcon image = new ImageIcon("src/aplicacion/Imagenes/buttonColor1.png");
        backButton.setIcon(image);
    }//GEN-LAST:event_backButtonMouseExited

    private void confirmButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseEntered
        ImageIcon image = new ImageIcon("src/aplicacion/Imagenes/buttonColor2.png");
        confirmButton.setIcon(image);
    }//GEN-LAST:event_confirmButtonMouseEntered

    private void confirmButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseExited
        ImageIcon image = new ImageIcon("src/aplicacion/Imagenes/buttonColor1.png");
        confirmButton.setIcon(image);
    }//GEN-LAST:event_confirmButtonMouseExited

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        Boolean esMayor = true;
        int contador=0;
        int cantidad = 0;
        Statement stmt = null;
        ResultSet name = null;
        try {
            stmt = sql.getConnection().createStatement();
            } catch (SQLException ex) {
            System.out.println(ex);;
            }        
        for(int i=0;i<Itemnumdisp;i++){
            
            String selectcantidad = "Select Cantidad from Dispositivo where DispoID = " + DispoComp[i];
                try {
                    name = stmt.executeQuery(selectcantidad);
                } catch (SQLException ex) {
                    Logger.getLogger(InsertDispositivo.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    while(name.next()){
                    cantidad = name.getInt(1);}
                } catch (SQLException ex) {
                    Logger.getLogger(InsertDispositivo.class.getName()).log(Level.SEVERE, null, ex);
                }
            int temp=0; 
            for(int b=0;b<DispoComp.length;b++){
                if(DispoComp[i] == DispoComp[b]){
                    temp++;
                }
            }
            
            if(temp > cantidad){
                esMayor=false;
            }
            
        }
        
        for(int i=0;i<ItemnumAcc;i++){
            
            String selectcantidad = "Select Cantidad from Accesorio where AccID = " + AccComp[i];
                try {
                    name = stmt.executeQuery(selectcantidad);
                } catch (SQLException ex) {
                    Logger.getLogger(InsertDispositivo.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    while(name.next()){
                    cantidad = name.getInt(1);}
                } catch (SQLException ex) {
                    Logger.getLogger(InsertDispositivo.class.getName()).log(Level.SEVERE, null, ex);
                }
            int temp=0; 
            for(int b=0;b<AccComp.length;b++){
                if(AccComp[i] == AccComp[b]){
                    temp++;
                }
            }
            
            if(temp > cantidad){
                esMayor=false;
            }
            
        }
        
        
        if(cliIdTextField.getText() != "" && itemsToPurchaseTextArea.getText() != "" && esMayor){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
            Date date = new Date();
            String currentdate = sdf.format(date);
            String Query = "insert into Factura (ClientID,Fcompra) values ('" + cliIdTextField.getText() + "','" +
                    currentdate + "')";
            try {
                sql.executeQuery(Query);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            
            String noFactura = "";
            String selectFact = "Select NoFactura from Factura where Fcompra = '" + currentdate + "'";
            stmt = null;
            ResultSet factura = null;
            try {
            stmt = sql.getConnection().createStatement();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
            try {
            factura = stmt.executeQuery(selectFact);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
            try {
                while(factura.next()){
                noFactura = factura.getString(1);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InsertFactura.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(DispoComp[0] != 0){
                for(int i =0; i < Itemnumdisp;i++){
                    String facturadisp = "insert into Factura_dispositivo (NoFactura,DispoID) values ("
                            + noFactura + ", " + DispoComp[i] + ")";
                    try {
                        sql.executeQuery(facturadisp);
                    } catch (SQLException ex) {
                        Logger.getLogger(InsertFactura.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
                
                
            }
            
            if(AccComp[0] != 0){
                for(int i =0; i < ItemnumAcc;i++){
                    String facturaAcc = "insert into Factura_accesorio (NoFactura,AccID) values ("
                            + noFactura + ", " + AccComp[i] + ")";
                    try {
                        sql.executeQuery(facturaAcc);
                    } catch (SQLException ex) {
                        Logger.getLogger(InsertFactura.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
            }
            if(Itemnumdisp > 0){
            for(int i=0;i<Itemnumdisp;i++){
                cantidad = 0;
                String selectcantidad = "Select Cantidad from Dispositivo where DispoID = " + DispoComp[i];
                try {
                    name = stmt.executeQuery(selectcantidad);
                } catch (SQLException ex) {
                    Logger.getLogger(InsertDispositivo.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    while(name.next()){
                    cantidad = name.getInt(1);}
                } catch (SQLException ex) {
                    Logger.getLogger(InsertDispositivo.class.getName()).log(Level.SEVERE, null, ex);
                }
                cantidad = cantidad - 1;
                String update = "Update Dispositivo set Cantidad = " + cantidad + " where DispoID = " + DispoComp[i];
                try {
                    sql.executeQuery(update);
                } catch (SQLException ex) {
                    Logger.getLogger(InsertDispositivo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }}
            if(ItemnumAcc > 0){
            for(int i=0;i<ItemnumAcc;i++){
                cantidad = 0;
                String selectcantidad = "Select Cantidad from Accesorio where AccID = " + AccComp[i];
                try {
                    name = stmt.executeQuery(selectcantidad);
                } catch (SQLException ex) {
                    Logger.getLogger(InsertDispositivo.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    while(name.next()){
                    cantidad = name.getInt(1);}
                } catch (SQLException ex) {
                    Logger.getLogger(InsertDispositivo.class.getName()).log(Level.SEVERE, null, ex);
                }
                cantidad = cantidad - 1;
                String update = "Update Accesorio set Cantidad = " + cantidad + " where AccID = " + AccComp[i];
                try {
                    sql.executeQuery(update);
                } catch (SQLException ex) {
                    Logger.getLogger(InsertDispositivo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }}
            
            cliIdTextField.setText("");
            ItemnumAcc = 0;
            Itemnumdisp = 0;
            itemsToPurchaseTextArea.setText("");
            JOptionPane.showMessageDialog(null, "Data succesfully added");
        }
        else if(esMayor){
            JOptionPane.showMessageDialog(null, "Please Insert Data First");
        }
        else{
            JOptionPane.showMessageDialog(null, "Device or Accesory bought has exceeded Inventory");
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String addItem = "";
        ResultSet name = null;
        String ItemName = "";
        String ItemPrice = "";
        Statement stmt = null;
        try {
            stmt = sql.getConnection().createStatement();
        } catch (SQLException ex) {
            System.out.println(ex);;
        }
        if(tipoProdSelect.getSelectedIndex() == 0){
            DispoComp[Itemnumdisp] = Integer.parseInt(itemIdTextField.getText());
            Itemnumdisp++;
            addItem =   "Select e.ModNombre, s.DispPrecio From Modelo e, Dispositivo s "
                      + "Where e.ModID = (Select i.ModID from Dispositivo i "
                      + "Where i.DispoID = " + itemIdTextField.getText() + " ) " + "and s.DispoID = " + itemIdTextField.getText();
                    try {
            name = stmt.executeQuery(addItem);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
            try {
                while(name.next()){
                ItemName = name.getString(1);
                ItemPrice = name.getString(2);
                }
            } catch (SQLException ex) {
                Logger.getLogger(InsertFactura.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            AccComp[ItemnumAcc] = Integer.parseInt(itemIdTextField.getText());
            ItemnumAcc++;
            addItem = "Select AccNombre, AccPrecio From Accesorio "
                      + "Where AccID = " + itemIdTextField.getText();
            try {
            name = sql.executeQuery(addItem);
            } catch (SQLException ex) {
                System.out.println(ex);
                }
            try {
                while(name.next()){
                 ItemName = name.getString(1);
                 ItemPrice = name.getString(2);}
            } catch (SQLException ex) {
                System.out.println(ex);
                }
        }
        itemsToPurchaseTextArea.setText(itemsToPurchaseTextArea.getText() + ItemName + " -  $" + ItemPrice + "\n");
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void confirmButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMousePressed
        ImageIcon image = new ImageIcon("src/aplicacion/Imagenes/buttonColor1.png");
        confirmButton.setIcon(image);
    }//GEN-LAST:event_confirmButtonMousePressed

    private void backButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMousePressed
        ImageIcon image = new ImageIcon("src/aplicacion/Imagenes/buttonColor1.png");
        backButton.setIcon(image);
    }//GEN-LAST:event_backButtonMousePressed

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        this.setExtendedState(TableSelect.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void minimizeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseEntered
        minimizeButton.setBackground(new Color(146,147,149));
    }//GEN-LAST:event_minimizeLabelMouseEntered

    private void minimizeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseExited
        minimizeButton.setBackground(new Color(194,200,203));
    }//GEN-LAST:event_minimizeLabelMouseExited

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        exitButton.setBackground(new Color(211,22,34));
        exitLabel.setForeground(new Color(247,247,247));
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        exitButton.setBackground(new Color(194,200,203));
        exitLabel.setForeground(new Color(27,47,59));
    }//GEN-LAST:event_exitLabelMouseExited

    private void headerPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerPanelMouseDragged

    private void headerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerPanelMousePressed

    private void addButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseEntered
        ImageIcon image = new ImageIcon("src/aplicacion/Imagenes/buttonColor2.png");
        addButton.setIcon(image);
    }//GEN-LAST:event_addButtonMouseEntered

    private void addButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseExited
        ImageIcon image = new ImageIcon("src/aplicacion/Imagenes/buttonColor1.png");
        addButton.setIcon(image);
    }//GEN-LAST:event_addButtonMouseExited

    private void catalogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogMouseEntered
        ImageIcon image = new ImageIcon("src/aplicacion/Imagenes/buttonColor6.png");
        catalog.setIcon(image);
    }//GEN-LAST:event_catalogMouseEntered

    private void catalogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogMouseExited
        ImageIcon image = new ImageIcon("src/aplicacion/Imagenes/buttonColor7.png");
        catalog.setIcon(image);
    }//GEN-LAST:event_catalogMouseExited

    private void catalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogActionPerformed
        Catalog cat = new Catalog();
        cat.sql = this.sql;
        cat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_catalogActionPerformed

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
        ImageIcon image = new ImageIcon("src/aplicacion/Imagenes/buttonColor6.png");
        menu.setIcon(image);
    }//GEN-LAST:event_menuMouseEntered

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
        ImageIcon image = new ImageIcon("src/aplicacion/Imagenes/buttonColor7.png");
        menu.setIcon(image);
    }//GEN-LAST:event_menuMouseExited

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        mainMenu.sql = this.sql;
        this.dispose();
    }//GEN-LAST:event_menuActionPerformed

    private void editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseEntered
        ImageIcon image = new ImageIcon("src/aplicacion/Imagenes/buttonColor6.png");
        edit.setIcon(image);
    }//GEN-LAST:event_editMouseEntered

    private void editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseExited
        ImageIcon image = new ImageIcon("src/aplicacion/Imagenes/buttonColor7.png");
        edit.setIcon(image);
    }//GEN-LAST:event_editMouseExited

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        Database dbView = new Database();
        dbView.sql = this.sql;
        dbView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel blueStripe;
    private javax.swing.JButton catalog;
    private javax.swing.JLabel cliIDLabel;
    private javax.swing.JTextField cliIdTextField;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton edit;
    private javax.swing.JPanel exitButton;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JPanel facturaFormBG;
    private javax.swing.JLabel facturaLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton insert;
    private javax.swing.JLabel itemIdLabel;
    private javax.swing.JTextField itemIdTextField;
    private javax.swing.JTextArea itemsToPurchaseTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menu;
    private javax.swing.JPanel minimizeButton;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JLabel modIDLabel2;
    private javax.swing.JLabel purchaseLabel;
    private javax.swing.JPanel redStripe;
    private javax.swing.JComboBox<String> tipoProdSelect;
    private javax.swing.JPanel windowActions;
    // End of variables declaration//GEN-END:variables
}
