/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class InsertSuplidor extends javax.swing.JFrame {

    /**
     * Creates new form InsertSuplidor
     */
    public Statement sql;
    public InsertSuplidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supFormBG = new javax.swing.JPanel();
        supLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        supNombreTextField = new javax.swing.JTextField();
        calleLabel = new javax.swing.JLabel();
        supCalleTextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        supSectorTextField = new javax.swing.JTextField();
        sectorLabel = new javax.swing.JLabel();
        supCiudadTextField = new javax.swing.JTextField();
        countryLabel = new javax.swing.JLabel();
        supPaisTextField = new javax.swing.JTextField();
        numberLabel = new javax.swing.JLabel();
        supNumTelefonoTextField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        supFormBG.setBackground(new java.awt.Color(247, 247, 247));
        supFormBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        supLabel.setForeground(new java.awt.Color(27, 47, 59));
        supLabel.setText("Supplier");
        supFormBG.add(supLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        nombreLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(27, 47, 59));
        nombreLabel.setText("Name");
        supFormBG.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        supFormBG.add(supNombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, -1));

        calleLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        calleLabel.setForeground(new java.awt.Color(27, 47, 59));
        calleLabel.setText("Street");
        supFormBG.add(calleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        supFormBG.add(supCalleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, -1));

        cityLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cityLabel.setForeground(new java.awt.Color(27, 47, 59));
        cityLabel.setText("City");
        supFormBG.add(cityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        supFormBG.add(supSectorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, -1));

        sectorLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        sectorLabel.setForeground(new java.awt.Color(27, 47, 59));
        sectorLabel.setText("Sector");
        supFormBG.add(sectorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        supFormBG.add(supCiudadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, -1));

        countryLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        countryLabel.setForeground(new java.awt.Color(27, 47, 59));
        countryLabel.setText("Country");
        supFormBG.add(countryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));
        supFormBG.add(supPaisTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, -1));

        numberLabel.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        numberLabel.setForeground(new java.awt.Color(27, 47, 59));
        numberLabel.setText("Phone No.");
        supFormBG.add(numberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));
        supFormBG.add(supNumTelefonoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 130, -1));

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        supFormBG.add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 110, 40));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        supFormBG.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supFormBG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supFormBG, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         TableSelect selectTable = new TableSelect();
                selectTable.sql = this.sql;
                selectTable.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        if(        supCalleTextField.getText() != "" 
                && supCiudadTextField.getText() != "" 
                && supNombreTextField.getText() != ""
                && supNumTelefonoTextField.getText() != ""
                && supPaisTextField.getText() != ""
                && supSectorTextField.getText() != ""){
            String Query = "insert into Suplidor (SupNombre, SupCalle, SupSector,"
                    + " SupCiudad, SupPaís, SupNumTeléfono) values ('" 
                    + supNombreTextField.getText() + "','" 
                    + supCalleTextField.getText() + "','" 
                    + supSectorTextField.getText() + "','" 
                    + supCiudadTextField.getText() + "','" 
                    + supPaisTextField.getText() + "','"
                    + supNumTelefonoTextField.getText() + "')";
            try {
                sql.executeQuery(Query);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            supNombreTextField.setText("");
            supCalleTextField.setText("");
            supSectorTextField.setText("");
            supCiudadTextField.setText("");
            supPaisTextField.setText("");
            supNumTelefonoTextField.setText("");
            JOptionPane.showMessageDialog(null, "Data succesfully added");
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Insert Data First");
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertSuplidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertSuplidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertSuplidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertSuplidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertSuplidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calleLabel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel sectorLabel;
    private javax.swing.JTextField supCalleTextField;
    private javax.swing.JTextField supCiudadTextField;
    private javax.swing.JPanel supFormBG;
    private javax.swing.JLabel supLabel;
    private javax.swing.JTextField supNombreTextField;
    private javax.swing.JTextField supNumTelefonoTextField;
    private javax.swing.JTextField supPaisTextField;
    private javax.swing.JTextField supSectorTextField;
    // End of variables declaration//GEN-END:variables
}
