/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import java.sql.*;

/**
 *
 * @author Usuario
 */
public class TableSelect extends javax.swing.JFrame {

    /**
     * Creates new form TableSelect
     */
    
    public Statement sql;
    
    public TableSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tabla = new javax.swing.JComboBox<>();
        continueButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Supplier", "Device", "Model", "Brand", "Accessory", "Receipt", "Accessory Supply", "Device Supply" }));
        Tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TablaActionPerformed(evt);
            }
        });
        jPanel1.add(Tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 210, 50));

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        jPanel1.add(continueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        // TODO add your handling code here:
        int IdTableSelect = Tabla.getSelectedIndex();
        switch(IdTableSelect){
            case 0:
                InsertEmpleado insEmp = new InsertEmpleado();
                insEmp.sql = this.sql;
                insEmp.setVisible(true);
                this.dispose();
                break;

            case 1:
                InsertSuplidor insSup = new InsertSuplidor();
               
                insSup.setVisible(true);
                this.dispose();
                break;
            case 2:
                InsertDispositivo insDispo= new InsertDispositivo();
               
                insDispo.setVisible(true);
                this.dispose();
                break;
            case 3:
                InsertModelo insMod= new InsertModelo();
               
                insMod.setVisible(true);
                this.dispose();
                break;    
            case 4:
                InsertMarca insMarca = new InsertMarca();
                insMarca.sql = this.sql;
                insMarca.setVisible(true);
                this.dispose();
                break;
            case 5: 
                InsertAccesorio insAcc = new InsertAccesorio();
               
                insAcc.setVisible(true);
                this.dispose();     
                break;
            case 6:
                InsertFactura insFactura = new InsertFactura();
               
                insFactura.setVisible(true);
                this.dispose();
                break;
            case 7:
                InsertAccSuplidor insAccSup = new InsertAccSuplidor();
               
                insAccSup.setVisible(true);
                this.dispose();
                break;
            case 8:
                InsertDispSuplidor insDispSup = new InsertDispSuplidor();
               
                insDispSup.setVisible(true);
                this.dispose();
                break;
            default :
                break;    
        }
    }//GEN-LAST:event_continueButtonActionPerformed

    private void TablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TablaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Tabla;
    private javax.swing.JButton continueButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
